import assert from "node:assert/strict";
import test from "node:test";
import { EventEmitter } from "node:events";
import type { Bot } from "mineflayer";
import { Vec3 } from "vec3";
import { botFixture } from "../../../test-support/bot.js";
import { arrowFlight, trackArrowFlights } from "./arrow-flight.js";

test("flight advances across zero-delta packets and reconciles reflection without reusing launch position", () => {
  const bot = botFixture();
  bot._client = new EventEmitter() as Bot["_client"];
  bot.world.raycast = () => null;
  const entity = { id: 4, name: "arrow", position: new Vec3(0, 65, 10), velocity: new Vec3(0, 0.15, -1.7) } as unknown as Bot["entity"];
  bot.entities[4] = entity;
  let now = 0;
  const tracker = trackArrowFlights(bot, () => now);
  const secondOwner = trackArrowFlights(bot, () => now);
  assert.equal(bot._client.listenerCount("spawn_entity"), 1);
  assert.equal(arrowFlight(bot, entity, now).positionAt, null, "pre-existing entities have unknown observation age");
  bot._client.emit("spawn_entity", { entityId: 4 });
  now = 50;
  bot._client.emit("entity_move_look", { entityId: 4, dX: 0, dY: 0, dZ: 0 });
  const first = arrowFlight(bot, entity, 50);
  assert.equal(first.positionAt, 0, "zero displacement does not refresh position freshness");
  assert.equal(first.position.z, 8.3);
  const later = arrowFlight(bot, entity, 300);
  assert.ok(later.position.z < 0.1);
  assert.equal(entity.position.z, 10, "authoritative observation is untouched");
  now = 300;
  entity.velocity.set(0, -0.04, 0.16);
  bot._client.emit("entity_velocity", { entityId: 4 });
  assert.equal(arrowFlight(bot, entity, 300).velocityAt, 300);
  assert.equal(arrowFlight(bot, entity, 300).positionAt, 0);
  assert.equal(arrowFlight(bot, entity, 300).position.z, later.position.z);
  assert.equal(arrowFlight(bot, entity, 350).velocity.z, 0.16 * 0.99);
  entity.position.set(0, 65, 1.1);
  bot._client.emit("sync_entity_position", { entityId: 4 });
  assert.equal(arrowFlight(bot, entity, 300).position.z, 1.1);
  entity.velocity.set(0, 0, 0);
  bot._client.emit("entity_velocity", { entityId: 4 });
  assert.equal(arrowFlight(bot, entity, 1000).position.z, 1.1);
  bot._client.emit("entity_destroy", { entityIds: [4] });
  entity.position.z = 42;
  assert.equal(arrowFlight(bot, entity, 1000).position.z, 42);
  tracker[Symbol.dispose]();
  assert.equal(bot._client.listenerCount("spawn_entity"), 1);
  secondOwner[Symbol.dispose]();
  assert.equal(bot._client.listenerCount("spawn_entity"), 0);
});

test("terrain stops extrapolation and respawn discards the previous flight", () => {
  const bot = botFixture();
  bot._client = new EventEmitter() as Bot["_client"];
  const entity = { id: 8, name: "arrow", position: new Vec3(0, 65, 10), velocity: new Vec3(0, 0, -1) } as unknown as Bot["entity"];
  bot.entities[8] = entity;
  using _tracker = trackArrowFlights(bot, () => 0);
  bot.world.raycast = (() => ({})) as unknown as typeof bot.world.raycast;
  assert.equal(arrowFlight(bot, entity, 100).velocity.norm(), 0);
  bot.emit("respawn");
  assert.equal(arrowFlight(bot, entity, 100).velocity.norm(), 1);
});
